### ISSUE TITLE
the question to use this package

### ISSUE THREAD

**Issue by HaveF** [naoufal/universal-config#3]
Thanks for your time to make this package!

I have two questions to ask, 
1. why you emphasis the code below?
```js
// Client JavaScript

import config from "universal-config";

config.get("AWS:accessKey");   // undefined
config.get("FACEBOOK_APP_ID"); // Outputs your FACEBOOK_APP_ID
```

Is it for security reason? Not let client to know the key of server?

2. If I have a id to share between client, and server, in development/production
I have to put the id to `dev.js`, and `prod.js`, do I understand correctly?

**Comment by naoufal** [comment]
Yeah, it's for security.  You wouldn't want secret keys leaking in your client code.

Any universal configs, should be kept in `client.js` --  both the client and server will have acess to those.
